### PR TITLE
Intersection-Point-in-Y-Shapped-Linked-Lists

### PR DESCRIPTION
**Pull request by Himanshi2511**
i have made the PR for Intersection-Point-in-Y-Shapped-Linked-Lists. pls review it and merge the PR and close the issue #82.
kindly add the hactoberfest level.

### CODE REVIEW

**Comment by Himanshi2511** [comment]
@raushanraj358. Kindly review my PR once.

**Comment by raushanraj358** [comment]
Hi, will review tomorrow.

**Comment by Himanshi2511** [comment]
@raushanraj358 pls review my PR

**Comment by raushanraj358** [comment]
Done.

**Pull request merged**
